version: '2'

services: 
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    volumes:
      - /etc/nginx/certs
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports: 
      - 80:80
      - 443:443
  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes_from: [nginx-proxy]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - DEFAULT_EMAIL=${DEFAULT_EMAIL}
    depends_on:
      - nginx-proxy